name: docker in macos


on:
    push:
        branches:
            - main
        paths:
            - 'dockerfile'
            - '.github/workflows/docker.yml'
    workflow_dispatch:

jobs:
    docker-build:
        runs-on: macos-13
        steps:
        - name: Set up Docker
          run: brew install docker colima
        - name: Build the Docker image
          run: |
            colima start
            # For testcontainers to find the Colima socket
            # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
            sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
            docker build --rm -f dockerfile -t my-image .