name: docker in macos

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-13
        steps:
        - uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Build the Docker image
          run: docker build --rm -f Dockerfile -t my-image .