name: docker in macos


on:
    push:
        branches:
            - main
        paths:
            - 'dockerfile'
            - '.github/workflows/docker.yml'
    workflow_dispatch:

jobs:
    docker-build:
        runs-on: macos-13
        steps:
        - name: Set up Docker
          uses: douglascamata/setup-docker-macos-action@v1-alpha
        - name: Build the Docker image
          run: |
            docker build --rm -f dockerfile -t my-image .