name: docker in macos

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-13
        steps:
        - uses: actions/checkout@v4
        - name: Build the Docker image
          run: docker build --rm -f Dockerfile -t my-image .