name: docker in macos

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-13
        steps:
        - name: Set up Docker
          run: brew install docker colima
        - name: Build the Docker image
          run: |
            colima start
            docker build --rm -f Dockerfile -t my-image .